### ISSUE TITLE
Do Cognatesets have names?

### ISSUE THREAD

**Issue by fmatter** [cldf/cldfviz#13]
The [template](https://github.com/cldf/cldfviz/blob/text/src/cldfviz/templates/text/CognatesetTable_detail.md) for a Cognateset assumes that it has a name (no checking is done).
This clashes with the [default CLDF specification](https://github.com/cldf/cldf/tree/master/components/cognatesets) of the cognate set component.
I've wondered about how to structure this in CLDF before -- the usual case is that the cognates belonging to a cognate set go back to a single proto-form, which would then be the 'name' of the cognate set. On the other hand, we may also model the proto-language and represent this proto-form as a `Form` of said language..
In the latter case, `Name` would not make sense for a cognate set, but in the former it is crucial.
Is there a canonical way to do this? It should be reflected in both the CLDF specification and the markdown template.

(also, I start to realize that much of my questions and ideas around CLDF-markdown are primarily about how to model different things in CLDF. Where is the proper place for such discussions?)

**Comment by xrotwang** [comment]
I think we have to make a choice at some point whether we want the templates to be generically applicable or "opinionated" (i.e. assuming more than just valid CLDF). `clld` tries to be generically applicable in e.g. the RDF templates. So there's some heuristics builtin for retrieving a label for an object, looking up `name` first, defaulting to `id` or even `pk`. While I think that's adequate, e.g. to fill in a `dc:title` field in RDF, it does seem to go against ["explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/).

No in the case here, I'd say that if a dataset has a `CognatesetTable`, but no `name` in this table, lists of cognates in a set should just be rendered using `[](CognateTable?cognatesetReference=...#cldf:__all__)`. Alternatively, a user could provide their own template (which may admittedly not be for everyone).

Regarding the question where to discuss CLDF modeling issues: I'd say issues at https://github.com/cldf/cdf are the right place. And regarding the question whether there should be two types of Cognatesets, one with required name, the other without: I'm not sure this should be specified by CLDF means. I could see all sorts of informal decisions going into what to store in Cognateset. E.g. one could use the `name` to store the labels of corresponding "traits" in a Nexus file, ...
