### ISSUE TITLE
Reference list?

### ISSUE THREAD

**Issue by fmatter** [cldf/cldfviz#14]
Cited references should be gathered and printed automatically at the end, right? How could that be accomplished?

**Comment by xrotwang** [comment]
There's already a template to "print" all sources. We'd have to find a way to figure out which ones have been cited.

**Comment by xrotwang** [comment]
This mechanism should also be available for collections of CLDF markdown documents, e.g. all grambank wiki pages; and maybe support per-doc reference lists as well as per collection reference lists.
