### ISSUE TITLE
Use page ranges in citation?

### ISSUE THREAD

**Issue by fmatter** [cldf/cldfviz#15]
I see that bibkey[pages] works when used as e.g. the `Source` of a `CognateSet`; can we do the same in running text?

**Comment by xrotwang** [comment]
I'd guess for the generic case of just citing a source this would be another URL param, e.g.
```
[](Source?pages=21#cldf:Matter2020)
```

For objects that "cite" a source via the `Source` column in the CLDF data, the template corresponding to the object should pull the pages from there.

**Comment by fmatter** [comment]
Has this have anything to do with the `pages` parameter in [Source_detail.md](https://github.com/cldf/cldfviz/blob/main/src/cldfviz/templates/text/Source_detail.md)?

**Comment by xrotwang** [comment]
I think we have to distinguish here between a source and a reference (i.e. citing a source).

**Comment by xrotwang** [comment]
I think the `pages` parameter in Source_detail.md was a mistake (of documentation - it wasn't really used).

As I said, we need to distinguish between a source and a reference of this source. The things you find in CLDF `source` columns (somewhat ironically) are lists of references. These come with a citation context - typically page information. Rendering the corresponding CLDF object - i.e. the row of the table - will insert citation + page info.

Now a simple reference in text , that is not associated with any "complex" CLDF object, would simply be a link to the corresponding source object in mode `ref` - and page info could be added in the text surrounding it:
```shell
$ cldfbench cldfviz.text --text-string "[](Source?ref&with_internal_ref_link#cldf:Peterson2017): 44" tests/StructureDataset/StructureDataset-metadata.json 
[Peterson 2017](#source-Peterson2017): 44
```

**Comment by fmatter** [comment]
> Now a simple reference in text , that is not associated with any "complex" CLDF object, would simply be a link to the corresponding source object in mode ref - and page info could be added in the text surrounding it:

Of course, `[](Source?ref&with_internal_ref_link#cldf:Peterson2017): 44` appears unnecessarily complicated from an author's point of view. Also, you often find citations of the form `Peterson (2017: 44)` in linguistics papers, where year and page are closer together than year and the rest of the source... 

I guess this will have to be the job of whatever markdown preprocessor a given project uses; from the author's POV I could see something like `[src](Peterson2017[44]))` and `[psrc](Peterson2017[44]))`

**Comment by xrotwang** [comment]
Ok, I'm running into this issue now myself. So ... will implement! :)
