### ISSUE TITLE
error: 'Config /home/.../.config/cldf/catalog.ini has no entry for glottolog'

### ISSUE THREAD

**Issue by lemontree210** [cldf/cldfviz#25]
I tried building a sample map for my CLDF dataset and got the following error message after running `cldfbench cldfviz.map` (with the path to my dataset and options listed in the [example](https://github.com/cldf/cldfviz/blob/main/docs/map.md#examples)):

```
'Config /home/<my_username>/.config/cldf/catalog.ini has no entry for glottolog'
```

I then replicated the steps in the [example](/cldf/cldfviz/blob/main/docs/map.md#examples) to make sure it's not my dataset or the way I type the command that are causing the problem.

After downloading WALS CLDF data and running 

```bash
cldfbench cldfviz.map wals-2020.1/StructureDataset-metadata.json --base-layer Esri_WorldPhysical --pacific-centered
```
I get the same error message. No HTML file was created.

**Comment by fmatter** [comment]
I have never used `cldfviz.map` (can't help you with the traceback), but I'd agree that running it without a glottolog clone would be nice.

However, `pyglottolog` is part of the [requirements](https://github.com/cldf/cldfviz/blob/a52a6a932b5abe882ad2bf6bce62776a0545da88/setup.py#L33).

**Comment by lemontree210** [comment]
> However, pyglottolog is part of the [requirements](https://github.com/cldf/cldfviz/blob/a52a6a932b5abe882ad2bf6bce62776a0545da88/setup.py#L33).

Thanks, yes, I tried uninstalling them both and then installing `cldfviz` again, and `pyglottolog` got installed. It was my glitch then.

**Comment by lemontree210** [comment]
OK, based on the `TypeError` message I figured out what the problem was: the exception was triggered by the possibility for a language to have more than one glottocode that I had encoded in my metadata. 

CLDF formally allows any field, glottocode included, to have multiple values. So in my dataset there are some languages that have 2 or more glottocodes. But the exception will be raised even if there are no actual languages that have multiple glottocodes. The actual trigger is the JSON metadata file where I put (using `pycldf`) the `"separator: "; "` parameter for `Glottocode` field. If I delete this line, `cldfviz` creates the map successfully. Otherwise, the `Glottolog` field is read as a list for every language, which surprises `cldfviz`.

As for the coordinates in my dataset, there is only one set of coordinates per language. I guess that `cldfviz` takes coordinates from Glottolog rather than from my coordinates in the dataset.

**Comment by LinguList** [comment]
@lemontree210, could you point us to your dataset, or parts of it, so we can have a look? If coordinates are taken from Glottolog rather from the CLDF itself, where you have your languages table, that would surprise me, so we should doublecheck here. Note that the original mapping code was based on examples with distinct geocoordinates where glottocodes might be the same or missing for individual varieties. 

For more examples, you can check https://github.com/lexibank/seabor/blob/main/workflow.md based on our study in [open research europe](https://doi.org/10.12688/openreseurope.13843.3).

**Comment by lemontree210** [comment]
Thanks! No no, I'm not saying the coordinates were indeed taken from Glottolog, I was just guessing that could be the case. I think I should just change some coordinates drastically and see what happens on the map.
The CLDF dataset I generated with `pycldf` (definitely still a work in progress!) is available [here](https://github.com/lemontree210/langworld_db_data/tree/master/data/cldf)
I set up a 'playground' repository for `cldfbench`/`cldfviz` but it uses the same data (I imported them with `git subtree`).

**Comment by LinguList** [comment]
Thanks for sharing the data. BTW: you generate structural data, it is recommendable to do so now with [cldfbench](https://github.com/cldf/cldfbench), as this will take care of some potential problems and offer more possibilities afterwards.

**Comment by xrotwang** [comment]
> As for the coordinates in my dataset, there is only one set of coordinates per language. I guess that `cldfviz` takes coordinates from Glottolog rather than from my coordinates in the dataset.

No. `cldfviz.map` should use the coordinates from your dataset preferentially, see https://github.com/cldf/cldfviz/blob/a52a6a932b5abe882ad2bf6bce62776a0545da88/src/cldfviz/multiparameter.py#L22-L33

**Comment by xrotwang** [comment]
> CLDF formally allows any field, glottocode included, to have multiple values. So in my dataset there are some languages that have 2 or more glottocodes. But the exception will be raised even if there are no actual languages that have multiple glottocodes. The actual trigger is the JSON metadata file where I put (using `pycldf`) the `"separator: "; "` parameter for `Glottocode` field. If I delete this line, `cldfviz` creates the map successfully. Otherwise, the `Glottolog` field is read as a list for every language, which surprises `cldfviz`.

See #26

**Comment by lemontree210** [comment]
> No. cldfviz.map should use the coordinates from your dataset preferentially, see 

Ok, I see

> See https://github.com/cldf/cldfviz/issues/26

Thanks :)

> You generate structural data, it is recommendable to do so now with [cldfbench](https://github.com/cldf/cldfbench), as this will take care of some potential problems and offer more possibilities afterwards.

I'm trying to do as much as possible from within the Python script and I couldn't yet figure out how to do it with `cldfbench`. So I figured, I'll just use `pycldf` then. So in my [main.py](https://github.com/lemontree210/langworld_db_data/blob/master/langworld_db_data/main.py) I run some of my own checks, then generate some Markdown (for internal discussion) and then create CLDF:

https://github.com/lemontree210/langworld_db_data/blob/64d948e8dc53202778a8e4e620f0d4db1e72dff8/langworld_db_data/main.py#L25

After that I actually still have to resort to `cldfbench` CLI to validate the dataset:

```bash
cldf validate data/cldf/StructureDataset-metadata.json
```
I would prefer to run validation from within [main.py](https://github.com/lemontree210/langworld_db_data/blob/master/langworld_db_data/main.py) if I knew how. 

If this is not possible, I guess I'll have to create a makefile that runs main.py with my internal procedures and then `cldfbench` for creation and validation of the CLDF dataset.

**Comment by xrotwang** [comment]
Since `cldfviz` 0.11 it is no longer required to have a local copy of [glottolog/glottolog](https://github.com/glottolog/glottolog) to access Glottolog metadata. Instead, commands requiring Glottolog data now have a `--glottolog-cldf` option, which accepts any kind of [dataset locator](https://github.com/cldf/cldf/blob/master/extensions/discovery.md), e.g.  `--glottolog-cldf https://raw.githubusercontent.com/glottolog/glottolog-cldf/v4.7/cldf/cldf-metadata.json`.
