### ISSUE TITLE
Map with only one feature

### ISSUE THREAD

**Issue by AnnikaTjuka** [cldf/cldfviz#29]
@xrotwang @LinguList I would like to create a map with only one feature and a color legend for `True`, `False`, and `Missing` values. 

I used the following command:
```
cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#008000","False":"#DC143C"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=25 --parameters=SkinAndBark --missing-value "#808080" --output=Colexification-Skin-Bark
```
And also some variations of the command, for example, adding the missing values as `"?":"#808080"`.

Here is the current output:
![Colexification-Skin-Bark](https://user-images.githubusercontent.com/45693807/167116762-2c76f177-ab3a-4254-9428-63117df17b27.jpg)

The missing values (= grey dots) don't appear in the legend on the right. Is there a way to integrate them?

**Comment by LinguList** [comment]
@AnnikaTjuka, @johenglisch, maybe it is because of the new CLDF data, which is still in one point different from lexibank-analysed? 

This is the body-object data (values.csv):

```
ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source
bantubvd-1-AnkleAndKnot,bantubvd-1,AnkleAndKnot,?,,,
bantubvd-1-ArmAndBranch,bantubvd-1,ArmAndBranch,False,ArmAndBranch-False,,
bantubvd-1-ArmAndValley,bantubvd-1,ArmAndValley,?,,,
```

This is lexibank-analysed, the values (lexicon-values.csv) for lexicon:

```
ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source
abrahammonpa-MonpaKalaktang-concepts,abrahammonpa-MonpaKalaktang,concepts,301,,,
abrahammonpa-MonpaKalaktang-forms,abrahammonpa-MonpaKalaktang,forms,324,,,
abrahammonpa-MonpaKalaktang-senses,abrahammonpa-MonpaKalaktang,senses,303,,,
abrahammonpa-MonpaKalaktang-LegAndFoot,abrahammonpa-MonpaKalaktang,LegAndFoot,?,LegAndFoot-None,,
abrahammonpa-MonpaKalaktang-ArmAndHand,abrahammonpa-MonpaKalaktang,ArmAndHand,?,ArmAndHand-None,,
```

**Comment by LinguList** [comment]
I think the code should be:

```
ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source
bantubvd-1-AnkleAndKnot,bantubvd-1,AnkleAndKnot,?,AnkleAndKnot-None,,
bantubvd-1-ArmAndBranch,bantubvd-1,ArmAndBranch,False,ArmAndBranch-False,,
bantubvd-1-ArmAndValley,bantubvd-1,ArmAndValley,?,ArmAndValley-None,,
```

**Comment by LinguList** [comment]
We also miss the missing values in the code table now, I think they are not added in the cldfbench script. So we should probably reintroduce those there.

**Comment by AnnikaTjuka** [comment]
For further discussion see: https://github.com/lexibank/tjukabodyobject/issues/12
