### ISSUE TITLE
Create ERD diagram for CLDF dataset

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfviz#38]
Download
- https://github.com/xerial/sqlite-jdbc/releases/download/3.39.4.1/sqlite-jdbc-3.39.4.1.jar
- https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar

Run
```
cldf createdb ... db.sqlite
java -jar schemaspy-6.1.0.jar -t sqlite-xerial -db db.sqlite -sso -s public -o tmp -dp drivers/ -cat % -vizjs
mv tmp/diagrams/summary/relationships.real.large.svg out.svg
rm -rf tmp
```

**Comment by SimonGreenhill** [comment]
Oh -- this will be super useful.

**Comment by xrotwang** [comment]
```
$ cldfbench cldfviz.erd https://zenodo.org/record/7322688 wacl.svg --schemaspy-jar ext/schemaspy.jar --sqlite-jar ext/sqlite.jar --format compact.svg
```
will create
![wacl](https://user-images.githubusercontent.com/870184/203302928-66c68c7f-5313-4380-ac43-4252aff25eed.svg)

**Comment by fmatter** [comment]
This is great, thank you!

**Comment by SimonGreenhill** [comment]
cool! thanks Robert
