### ISSUE TITLE
Subcommand to plot trees (via toytree)

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfviz#39]
With trees having landed in CLDF 1.2, we might provide support for plotting them.

**Comment by LinguList** [comment]
Would it be useful in this context to look at JS representations of trees, to allow for interactive views in HTML/JavaScript? Alternatively, one may also think about rudimentary dendrograms in Matplotlib, which work rather well.

**Comment by xrotwang** [comment]
toytree can output svg, which may (or may not) be editable enough?

**Comment by xrotwang** [comment]
We use such functionality already in phlorest, so as a first step, I'd just move this functionality here to make it more widely available.

![summary_tree](https://user-images.githubusercontent.com/870184/203806084-8b3524c1-7ce7-466c-9dc0-1c06c8153fec.svg)

**Comment by LinguList** [comment]
Yes, that is definitely fine.

**Comment by LinguList** [comment]
And if you already use it elsewhere, it is also much easier. The dendrograms in matplotlib are not THAT easy to handle.
