### ISSUE TITLE
Language labels do not appear on png-map

### ISSUE THREAD

**Issue by Tarotis** [cldf/cldfviz#46]
I am currently trying to create a cldfviz-map for the GATA dataset ([link here](https://github.com/cldf-datasets/gata))

Running the following the code: 
`cldfbench cldfviz.map ./ --parameters BasicWO --colormaps viridis --format png \
--width 20 --height 10 --dpi 300 --markersize 15 --with-ocean --projection Mollweide --language-labels`

It works a lot nicer than I expected, and it even automatically creates the map for both values that we have in the dataset for each language (old and new state). However, the language labels do not appear. Am I using the code wrong?

**Comment by Tarotis** [comment]
Similarly, adding `--padding-top 200 ` (or other values) does not change anything on the map. Is this about the order of options, or something else?

**Comment by xrotwang** [comment]
That's a limitation we should describe somewhere: Language labels only work with projection `PlateCarree` (the default). For other projections, markers are drawn as scatterplots, and I didn't figure out how to properly label these.

So, you may either use no `--projection` parameter and `--language-labels`, or `--language-labels` will have no effect.

**Comment by xrotwang** [comment]
The same goes for the `--padding` or `--extent` options, see https://github.com/cldf/cldfviz/blob/cc5879950a1abf0fd0397d4cf5d38956c756dab2/src/cldfviz/map/mpl.py#L94

**Comment by Tarotis** [comment]
Ah, I see, thanks for the info.
