### ISSUE TITLE
< and > must be escaped when rendering markdown

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfviz#50]
Infixation according to LGR is noted by enclosing the infix in `<...>`. If not escaped, this will be swallowed by markdown to HTML renderers.

**Comment by fmatter** [comment]
Request to make this optional?

**Comment by xrotwang** [comment]
> Request to make this optional?

Are there markdown renderers which would not treat `<ARTFOC>` as unknown HTML tag and just swallow it silently? pandoc, maybe?

**Comment by xrotwang** [comment]
Via https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre :

> If you have to display reserved characters such as <, >, &, and " within the <pre> tag, the characters must be escaped using their respective [HTML entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity).

**Comment by xrotwang** [comment]
@fmatter would it be ok to make this opt-out - i.e. defaulting to escaping?

**Comment by xrotwang** [comment]
The fix I just pushed allows opting out of the escaping behaviour both on cli level and on API level, i.e. when calling `cldfviz.text.render`. Does this work for you @fmatter ?
If not, feel free to re-open.

**Comment by xrotwang** [comment]
@fmatter for some context: I was working on `pyigt` recently and looked again at the Leipzig Glossing Rules. And Rule 9, when rendered without escaping, isn't very useful: https://github.com/cldf-datasets/lgr/blob/main/README.md#rule-9-infixes
:)

**Comment by fmatter** [comment]
Hi yes opt-out is fine. I don't know that I will run into problems yet, but it's good if I can turn it off.
